[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
bsc = "${BSC_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
monad = "${MONAD_RPC_URL}"
